#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:D:\mb-jpeg\system.xmp
#################################################################

XILINX_EDK_DIR = C:/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-7

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp D:/XilinxXUP/lib/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) \
                   $(MICROBLAZE_0_LIBG_OPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

BMP2JPG_MB_OUTPUT_DIR = bmp2jpg_mb
BMP2JPG_MB_OUTPUT = $(BMP2JPG_MB_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(BMP2JPG_MB_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(BMP2JPG_MB_OUTPUT) 

ALL_USER_ELF_FILES = $(BMP2JPG_MB_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM).do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM).do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM).do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti

MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

LIBRARIES =  \
       microblaze_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = bmp2jpg_mb_programclean 

CORE_STATE_DEVELOPMENT_FILES = D:\mb-jpeg\pcores\fsl_dct_v1_00_a\hdl\vhdl\fsl_dct.vhd

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_opb_wrapper.ngc \
implementation/debug_module_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/ilmb_bram_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/sysace_compactflash_wrapper.ngc \
implementation/leds_4bit_wrapper.ngc \
implementation/dipsws_4bit_wrapper.ngc \
implementation/pushbuttons_5bit_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/data_bram_0_wrapper.ngc \
implementation/data_bram_if_cntlr_0_wrapper.ngc \
implementation/dlmb_bram_wrapper.ngc \
implementation/microblaze_0_to_fsl_dct_0_wrapper.ngc \
implementation/fsl_dct_0_wrapper.ngc \
implementation/fsl_dct_0_to_microblaze_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION BMP2JPG_MB
#################################################################

BMP2JPG_MB_SOURCES = bmp2jpg_mb/bmp2jpg_mb.c bmp2jpg_mb/ColorConversion.c bmp2jpg_mb/dct.c bmp2jpg_mb/huffman.c bmp2jpg_mb/zzq.c 

BMP2JPG_MB_HEADERS = 

BMP2JPG_MB_CC = mb-gcc
BMP2JPG_MB_CC_SIZE = mb-size
BMP2JPG_MB_CC_OPT = -O0
BMP2JPG_MB_CFLAGS = 
BMP2JPG_MB_CC_SEARCH = # -B
BMP2JPG_MB_LIBPATH = -L./microblaze_0/lib/ # -L
BMP2JPG_MB_INCLUDES = -I./microblaze_0/include/ # -I
BMP2JPG_MB_LFLAGS = # -l
BMP2JPG_MB_CC_PREPROC_FLAG =   -Wp,-D__MICROBLAZE 
BMP2JPG_MB_CC_ASM_FLAG = # -Wa,
BMP2JPG_MB_CC_LINKER_FLAG = # -Wl,
BMP2JPG_MB_LINKER_SCRIPT = bmp2jpg_mb_linker_script.ld
BMP2JPG_MB_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(BMP2JPG_MB_LINKER_SCRIPT) 
BMP2JPG_MB_CC_DEBUG_FLAG =  -g 
BMP2JPG_MB_CC_PROFILE_FLAG = # -pg
BMP2JPG_MB_CC_GLOBPTR_FLAG= # -mxl-gp-opt
BMP2JPG_MB_MODE = executable
BMP2JPG_MB_LIBG_OPT = -$(BMP2JPG_MB_MODE) microblaze_0
BMP2JPG_MB_CC_SOFTMUL_FLAG= -mno-xl-soft-mul 
BMP2JPG_MB_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
BMP2JPG_MB_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
BMP2JPG_MB_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
BMP2JPG_MB_OTHER_CC_FLAGS= $(BMP2JPG_MB_CC_GLOBPTR_FLAG)  \
                  $(BMP2JPG_MB_CC_START_ADDR_FLAG) $(BMP2JPG_MB_CC_STACK_SIZE_FLAG) $(BMP2JPG_MB_CC_HEAP_SIZE_FLAG)  \
                  $(BMP2JPG_MB_CC_SOFTMUL_FLAG)  \
                  $(BMP2JPG_MB_CC_PREPROC_FLAG) $(BMP2JPG_MB_CC_ASM_FLAG) $(BMP2JPG_MB_CC_LINKER_FLAG)  \
                  $(BMP2JPG_MB_LINKER_SCRIPT_FLAG) $(BMP2JPG_MB_CC_DEBUG_FLAG) $(BMP2JPG_MB_CC_PROFILE_FLAG) 
