
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 7.1.2 EDK_H.12.5.1
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysace.h"

/*
* The configuration table for devices
*/

XSysAce_Config XSysAce_ConfigTable[] =
{
	{
		XPAR_SYSACE_COMPACTFLASH_DEVICE_ID,
		XPAR_SYSACE_COMPACTFLASH_BASEADDR
	}
};


